javac GraphNode.java
javac Graph.java
javac AdjacencyNode.java
javac FibonacciNode.java
javac FibonacciHeap.java
javac Global.java
javac TrieNode.java
javac Trie.java
javac routing.java
javac ssp.java
